apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: v1.17.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  valuesFrom:
    - name: cert-manager-values
      kind: ConfigMap
