---
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync"
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:https://s3.us-west-004.backblazeb2.com/astroterm-backup/${APP}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_MINIO_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_MINIO_SECRET_KEY}
