---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: app-template
  namespace: flux-system
spec:
  interval: 6h
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: 4.2.0
