---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 6h
  ref:
    tag: 0.32.0
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
