---
ipv4NativeRoutingCIDR: 10.244.0.0/16
routingMode: native

rollOutCiliumPods: true
kubeProxyReplacement: true

k8sServiceHost: localhost
k8sServicePort: 7445

ipam:
  mode: kubernetes
gatewayAPI:
  enabled: true
ipv4:
  enabled: true
l2announcements:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

operator:
  replicas: 1

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  privileged: true
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
