---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-operator
  namespace: &namespace flux-system
spec:
  targetNamespace: flux-system

  interval: 1h
  retryInterval: 5m
  timeout: 10m
  prune: true

  path: ./kubernetes/apps/flux-system/flux-operator/app

  sourceRef:
    kind: GitRepository
    name: home-infra

  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
