---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.15.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: storage
  valuesFrom:
    - name: prometheus-values
      kind: ConfigMap
