---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lexismc
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: 4.26.4
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: openebs
      namespace: storage
  valuesFrom:
    - name: lexismc-values
      kind: ConfigMap
