---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: mc-router-values
    files:
      - values.yaml=./values.yaml
generatorOptions:
  disableNameSuffixHash: true
