apiVersion: v1
kind: Secret
metadata:
    name: restic-config
    namespace: flux-system
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:xZsFgD9gAo7yhpiL1rRJwWrvJRV5WqXGoPbGA7El+a0=,iv:bHGtLjP2RkaVLuKFGLdIsuOrMzKmpqMYx0r4ctdCYUI=,tag:O8v8WTIdZfx7CamXJUGp8g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N67BNWWb/i/En4l39dQThlqbHlwBR/iq1A==,iv:bammfpj2rUuM+jtJ8AnDAchBYFZzL9BDJYP162irRqU=,tag:ykXJaka5zVh4+WThbTTVYg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IPbbxJ8/ApV37qAuMzG5B3rYAhreTXR55qJqoIq8BQ==,iv:oQz6Ffh6zy+zTInQ9VWMO3XGhuPmz3A7lw4TYM0gjDU=,tag:uF5O9hca0v8isIb0M0C37Q==,type:str]
sops:
    age:
        - recipient: age18ks3gzmrm0s8kx4z4kehxy7fl0zjltdl6vdh2j09pnef2hyj24es9whz0n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aC9sQ3pKbG9UWGNCMHow
            T3EwZlAvZ1IzOFMyZFJnZS8vR1hCY2ppc0JVCk91UDJGNlEzdFJiSFZFQVJ3Y282
            NnVQbXJPVEN2aGJTQjJnWU1kVHBBZVUKLS0tIHEwSmhNcHJpaGJrVFQ3VzlpY2wx
            S1NwSDRzL0dCSnFHdFcrZkV4bnhQTzQKwE2aDKHSrJXET5Klqn3znexEHCddQ67B
            8CFKxLtwXvNQLPC6nsVpNKA0eRZrqxaWJu07HnyqN4bdAzY8Msn/kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T05:38:09Z"
    mac: ENC[AES256_GCM,data:wXDkwj7kelxeBy79xC3hFnTAPEj1Qu48Acv/xJVe1hZJVAxKqTUghH+mGHX4KLvwt1Ij38XvBkbge6LCXeVsSk5roZvEGvJQcPpMV+Zq8Zq1Jx0jzVSku/qOJEg0zB1H8o4z/9Oo50M0N0rln7if79fun9wg8hKZok3QwQBOwLQ=,iv:Gls0Kn0gJJMXFQWYtyxzRaW//AZeBXrg58g3xTT/Zy0=,tag:PceyE0TYJt+j1xya92aFkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
